name: "gbraad's Dotfiles `dot` Action"
description: 'Wrapper for dot command execution on GitHub runners'
author: "Gerard Braad <me@gbraad.nl>"
inputs:
  run:
    description: 'Commands to run in ZSh'
    required: true
  upstream:
    description: "Whether to use the upstream repository when dotfiles not available"
    required: false
    default: "false"
outputs:
  exit_code:
    description: 'The exit code of the command'
    value: ${{ steps.dot-run.outputs.exit_code }}
runs:
  using: 'composite'
  steps:
    - name: Execute dot-command
      id: dot-run
      shell: bash
      run: |
        # Ensure dotfiles exists
        if [ ! -d "$HOME/.dotfiles" ]; then
          if [ "${{ inputs.upstream }}" = "true" ]; then
            git clone https://github.com/gbraad-dotfiles/upstream.git ~/.dotfiles --depth 2
          else
            git clone https://github.com/gbraad/dotfiles-stable.git ~/.dotfiles --depth 2
          fi         
        fi

        # Run the user-provided commands
        TEMP_SCRIPT=$(mktemp)
        trap 'rm -f "$TEMP_SCRIPT"' EXIT
        echo '#!/usr/bin/env zsh' > "$TEMP_SCRIPT"
        echo "${{ inputs.run }}" >> "$TEMP_SCRIPT"
        chmod +x "$TEMP_SCRIPT"
        "$HOME/.dotfiles/activate.sh" "$TEMP_SCRIPT"
        
        # Store the exit code as an output
        echo "exit_code=$?" >> $GITHUB_OUTPUT
